server:
  port: 9010


spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:33306/plumemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: plumemo
    password: plumemo
    driver-class-name: com.mysql.jdbc.Driver
