server:
  port: 9010


spring:
  banner:
    location: banner.txt
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:33306/plumemo
    username: plumemo
    password: plumemo
    type: com.alibaba.druid.pool.DruidDataSource
